# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label_index_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='label_index_map.proto',
  package='pokedex.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x15label_index_map.proto\x12\x0epokedex.protos\"-\n\x11LabelIndexMapItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"@\n\rLabelIndexMap\x12/\n\x04item\x18\x01 \x03(\x0b\x32!.pokedex.protos.LabelIndexMapItem')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LABELINDEXMAPITEM = _descriptor.Descriptor(
  name='LabelIndexMapItem',
  full_name='pokedex.protos.LabelIndexMapItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pokedex.protos.LabelIndexMapItem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='pokedex.protos.LabelIndexMapItem.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=86,
)


_LABELINDEXMAP = _descriptor.Descriptor(
  name='LabelIndexMap',
  full_name='pokedex.protos.LabelIndexMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='pokedex.protos.LabelIndexMap.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=152,
)

_LABELINDEXMAP.fields_by_name['item'].message_type = _LABELINDEXMAPITEM
DESCRIPTOR.message_types_by_name['LabelIndexMapItem'] = _LABELINDEXMAPITEM
DESCRIPTOR.message_types_by_name['LabelIndexMap'] = _LABELINDEXMAP

LabelIndexMapItem = _reflection.GeneratedProtocolMessageType('LabelIndexMapItem', (_message.Message,), dict(
  DESCRIPTOR = _LABELINDEXMAPITEM,
  __module__ = 'label_index_map_pb2'
  # @@protoc_insertion_point(class_scope:pokedex.protos.LabelIndexMapItem)
  ))
_sym_db.RegisterMessage(LabelIndexMapItem)

LabelIndexMap = _reflection.GeneratedProtocolMessageType('LabelIndexMap', (_message.Message,), dict(
  DESCRIPTOR = _LABELINDEXMAP,
  __module__ = 'label_index_map_pb2'
  # @@protoc_insertion_point(class_scope:pokedex.protos.LabelIndexMap)
  ))
_sym_db.RegisterMessage(LabelIndexMap)


# @@protoc_insertion_point(module_scope)
